name: 'RelativeCI agent'
description: 'Send webpack stats and CI build information to RelativeCI'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  token: 
    description: GitHub token
    required: true
  webpackStatsFile:
    description: 'Path to your local webpack stats file'
    required: true
  key:
    description: 'RelativeCI project key'
    required: true
  artifactName:
    description: 'Artifact to download when running in workflow_run'
    required: false
  slug:
    description: 'RelativeCI project slug'
    required: false
  includeCommitMessage:
    description: 'Include commit message'
    required: false
    default: true
  debug:
    description: 'Output debug info'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
