name: 'RelativeCI agent action'
description: 'Send webpack stats and CI build information to RelativeCI'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  webpackStatsFile:
    description: 'Path to your local webpack stats file'
    required: true
  key:
    description: 'RelativeCI project key'
    required: true
  slug:
    description: 'RelativeCI project slug'
    required: false
  debug:
    description: 'Output debug info'
    required: false
runs:
  using: "composite"
  steps:
    - name: Copy webpack stats file
      run: cp ${{ inputs.webpackStatsFile }} ${{ github.action_path}}/webpack-stats.json
      shell: bash

    - id: set-debug
      name: Set DEBUG environment variable
      env:
        INPUT_DEBUG: ${{ inputs.debug }}
      run: |
        RELATIVE_CI_DEBUG=$([ -z ${INPUT_DEBUG} ] && echo "" || echo "relative-ci:agent")
        echo "::set-output name=debug::${RELATIVE_CI_DEBUG}"
      shell: bash

    - run: cd ${{ github.action_path }} && ./node_modules/@relative-ci/agent/bin/index.js
      shell: bash
      env:
        RELATIVE_CI_KEY: ${{ inputs.key }}
        RELATIVE_CI_SLUG: ${{ inputs.slug }}
        DEBUG: ${{ steps.set-debug.outputs.debug }}
